#!/usr/bin/env python3
"""Offline validator: check fixture integrity.

Checks that every fixture file listed in fixtures/manifest.json exists
and has the recorded sha256. Also verifies that the fixture hashes
were generated by the current version of gen_fixtures.py (detected via
the `source` field pattern).

Usage:
    python3 validators/check_fixtures.py [--fixtures-dir runtime-spike/fixtures]
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def find_repo_root(start: Path) -> Path:
    p = start.resolve()
    while p != p.parent:
        if (p / "runtime-spike").is_dir():
            return p
        p = p.parent
    raise SystemExit("Cannot find repo root with runtime-spike/")


def validate(fixtures_dir: Path) -> list[str]:
    """Return list of error strings. Empty list = pass."""
    errors = []

    manifest_path = fixtures_dir / "manifest.json"
    if not manifest_path.exists():
        errors.append(f"MISSING: {manifest_path}")
        return errors

    manifest = json.loads(manifest_path.read_text())
    fixtures = manifest.get("fixtures", [])

    if not fixtures:
        errors.append("manifest.json has no fixtures listed")
        return errors

    for entry in fixtures:
        fname = entry.get("file", "")
        expected_hash = entry.get("sha256", "")

        fpath = fixtures_dir / fname
        if not fpath.exists():
            errors.append(f"MISSING FILE: {fname}")
            continue

        actual_hash = sha256_file(fpath)
        if not expected_hash:
            errors.append(f"MISSING HASH: {fname} has no sha256 in manifest")
        elif actual_hash != expected_hash:
            errors.append(
                f"HASH MISMATCH: {fname} expected={expected_hash[:16]}... "
                f"actual={actual_hash[:16]}..."
            )

    # Check for orphan fixture files (not in manifest)
    known = {e["file"] for e in fixtures}
    for fpath in fixtures_dir.iterdir():
        if fpath.name == "manifest.json":
            continue
        if fpath.name not in known:
            errors.append(f"ORPHAN FILE: {fpath.name} is not listed in manifest.json")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate RT-001 fixture integrity")
    parser.add_argument("--fixtures-dir", "-f", type=str,
                        default=None,
                        help="Path to fixtures directory")
    args = parser.parse_args()

    if args.fixtures_dir:
        fd = Path(args.fixtures_dir)
    else:
        repo_root = find_repo_root(Path.cwd())
        fd = repo_root / "runtime-spike" / "fixtures"

    errors = validate(fd)

    if errors:
        print(f"FIXTURE INTEGRITY: {len(errors)} error(s) found")
        for e in errors:
            print(f"  ERROR: {e}")
        return 1
    else:
        manifest = json.loads((fd / "manifest.json").read_text())
        count = len(manifest.get("fixtures", []))
        print(f"FIXTURE INTEGRITY: PASS ({count} fixture(s) verified)")
        for entry in manifest.get("fixtures", []):
            print(f"  {entry['file']}  sha256={entry['sha256'][:16]}...  used_by={entry.get('used_by', [])}")
        return 0


if __name__ == "__main__":
    sys.exit(main())