//! Content-free run binding over a harness-owned already-open byte stream.
//!
//! Callers must install read/write timeouts on the underlying Unix stream before
//! calling this module and must supply a freshly generated 32-byte host challenge
//! and an independent 32-byte binding secret. The binding secret never appears
//! on this stream.
//!
//! Later integration must pass that secret to the direct Host child over a
//! separate one-way anonymous inherited FD with an exact 32-byte read, and use
//! close-on-exec discipline for unrelated children. The supervised proxy retains
//! its in-memory copy. The bidirectional handshake stream alone is insufficient.
//! This module deliberately does not read environment, files, argv, receipts,
//! capabilities, or credentials, and it cannot authorize stock commands.

use sha2::{Digest, Sha256};
use std::fmt;
use std::io::{Read, Write};

pub const RUN_BINDING_VERSION: u8 = 1;
const MAX_FRAME: usize = 1024;
const MAX_FIELD: usize = 256;
const HELLO: u8 = 1;
const HOST_CHALLENGE: u8 = 2;
const PROXY_RESPONSE: u8 = 3;
const CHALLENGE_LEN: usize = 32;
const MAC_LEN: usize = 32;

/// Validated, content-free facts bound to a single harness run.
#[derive(Clone, PartialEq, Eq)]
pub struct RunBinding {
    pub run_id: String,
    pub proxy_origin: String,
    pub capability_digest: String,
}

impl fmt::Debug for RunBinding {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("RunBinding { redacted: true }")
    }
}

/// The only handshake failure surface. It intentionally does not retain frames,
/// identifiers, nonces, MACs, or I/O error strings.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RunBindingError {
    Io,
    Frame,
    Schema,
    Validation,
    Authentication,
    Replay,
}

impl fmt::Display for RunBindingError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Io => "run binding I/O failed",
            Self::Frame => "run binding frame rejected",
            Self::Schema => "run binding schema rejected",
            Self::Validation => "run binding facts rejected",
            Self::Authentication => "run binding authentication failed",
            Self::Replay => "run binding replay rejected",
        })
    }
}
impl std::error::Error for RunBindingError {}

/// Host-side single-use state. Reuse fails closed, including a duplicate call on
/// the same inherited stream.
pub struct HostRunBinding {
    challenge: [u8; CHALLENGE_LEN],
    binding_secret: [u8; 32],
    used: bool,
}

impl HostRunBinding {
    /// Both inputs must be independently generated by the harness from a CSPRNG.
    pub fn new(
        challenge: [u8; CHALLENGE_LEN],
        binding_secret: [u8; 32],
    ) -> Result<Self, RunBindingError> {
        if challenge.iter().all(|byte| *byte == 0) || binding_secret.iter().all(|byte| *byte == 0) {
            return Err(RunBindingError::Validation);
        }
        Ok(Self {
            challenge,
            binding_secret,
            used: false,
        })
    }

    pub fn handshake<S: Read + Write>(
        &mut self,
        stream: &mut S,
    ) -> Result<RunBinding, RunBindingError> {
        if self.used {
            return Err(RunBindingError::Replay);
        }
        self.used = true;
        let result = self.handshake_once(stream);
        self.binding_secret.fill(0);
        result
    }

    fn handshake_once<S: Read + Write>(
        &self,
        stream: &mut S,
    ) -> Result<RunBinding, RunBindingError> {
        let hello = decode_hello(&read_frame(stream)?)?;
        validate_hello(&hello)?;
        let host_mac = handshake_mac(&self.binding_secret, &hello, &self.challenge, b"host");
        write_frame(
            stream,
            &encode_fields(HOST_CHALLENGE, &[(1, &self.challenge), (2, &host_mac)])?,
        )?;
        let response = decode_response(&read_frame(stream)?)?;
        if !constant_time_eq(&response.challenge, &self.challenge)
            || response.capability_digest != hello.capability_digest
            || !constant_time_eq(
                &response.mac,
                &handshake_mac(&self.binding_secret, &hello, &self.challenge, b"proxy"),
            )
        {
            return Err(RunBindingError::Authentication);
        }
        Ok(RunBinding {
            run_id: hello.run_id,
            proxy_origin: hello.proxy_origin,
            capability_digest: hello.capability_digest,
        })
    }
}

impl Drop for HostRunBinding {
    fn drop(&mut self) {
        self.binding_secret.fill(0);
    }
}

/// Harness/proxy helper for tests and future supervised proxy integration.
/// It does not create capabilities and only speaks the bounded handshake.
pub fn proxy_handshake<S: Read + Write>(
    stream: &mut S,
    hello: RunBindingHello,
    mut binding_secret: [u8; 32],
) -> Result<(), RunBindingError> {
    let result = (|| {
        validate_hello(&hello)?;
        write_frame(
            stream,
            &encode_fields(
                HELLO,
                &[
                    (1, hello.run_id.as_bytes()),
                    (2, hello.proxy_origin.as_bytes()),
                    (3, hello.nonce.as_bytes()),
                    (4, hello.capability_digest.as_bytes()),
                ],
            )?,
        )?;
        let challenge = decode_challenge(&read_frame(stream)?)?;
        let expected = handshake_mac(&binding_secret, &hello, &challenge.challenge, b"host");
        if !constant_time_eq(&challenge.mac, &expected) {
            return Err(RunBindingError::Authentication);
        }
        let mac = handshake_mac(&binding_secret, &hello, &challenge.challenge, b"proxy");
        write_frame(
            stream,
            &encode_fields(
                PROXY_RESPONSE,
                &[
                    (1, &challenge.challenge),
                    (2, hello.capability_digest.as_bytes()),
                    (3, &mac),
                ],
            )?,
        )
    })();
    binding_secret.fill(0);
    result
}

#[derive(Clone, PartialEq, Eq)]
pub struct RunBindingHello {
    pub run_id: String,
    pub proxy_origin: String,
    pub nonce: String,
    pub capability_digest: String,
}

impl fmt::Debug for RunBindingHello {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("RunBindingHello { redacted: true }")
    }
}

fn read_frame<S: Read>(stream: &mut S) -> Result<Vec<u8>, RunBindingError> {
    let mut length = [0u8; 4];
    stream
        .read_exact(&mut length)
        .map_err(|_| RunBindingError::Io)?;
    let length = u32::from_be_bytes(length) as usize;
    if length == 0 || length > MAX_FRAME {
        return Err(RunBindingError::Frame);
    }
    let mut payload = vec![0; length];
    stream
        .read_exact(&mut payload)
        .map_err(|_| RunBindingError::Io)?;
    Ok(payload)
}
fn write_frame<S: Write>(stream: &mut S, payload: &[u8]) -> Result<(), RunBindingError> {
    if payload.is_empty() || payload.len() > MAX_FRAME {
        return Err(RunBindingError::Frame);
    }
    stream
        .write_all(&(payload.len() as u32).to_be_bytes())
        .map_err(|_| RunBindingError::Io)?;
    stream.write_all(payload).map_err(|_| RunBindingError::Io)?;
    stream.flush().map_err(|_| RunBindingError::Io)
}

fn encode_fields(kind: u8, fields: &[(u8, &[u8])]) -> Result<Vec<u8>, RunBindingError> {
    let mut out = vec![kind, RUN_BINDING_VERSION];
    for (tag, value) in fields {
        if value.len() > MAX_FIELD {
            return Err(RunBindingError::Frame);
        }
        out.push(*tag);
        out.extend_from_slice(&(value.len() as u16).to_be_bytes());
        out.extend_from_slice(value);
    }
    Ok(out)
}
fn decode_fields(
    frame: &[u8],
    expected_kind: u8,
    tags: &[u8],
) -> Result<Vec<Vec<u8>>, RunBindingError> {
    if frame.len() < 2 || frame[0] != expected_kind || frame[1] != RUN_BINDING_VERSION {
        return Err(RunBindingError::Schema);
    }
    let mut values: Vec<Option<Vec<u8>>> = vec![None; tags.len()];
    let mut cursor = 2;
    while cursor < frame.len() {
        if frame.len() - cursor < 3 {
            return Err(RunBindingError::Frame);
        }
        let tag = frame[cursor];
        let length = u16::from_be_bytes([frame[cursor + 1], frame[cursor + 2]]) as usize;
        cursor += 3;
        if length > MAX_FIELD || frame.len() - cursor < length {
            return Err(RunBindingError::Frame);
        }
        let index = tags
            .iter()
            .position(|known| *known == tag)
            .ok_or(RunBindingError::Schema)?;
        if values[index].is_some() {
            return Err(RunBindingError::Schema);
        }
        values[index] = Some(frame[cursor..cursor + length].to_vec());
        cursor += length;
    }
    values
        .into_iter()
        .map(|value| value.ok_or(RunBindingError::Schema))
        .collect()
}

fn decode_hello(frame: &[u8]) -> Result<RunBindingHello, RunBindingError> {
    let fields = decode_fields(frame, HELLO, &[1, 2, 3, 4])?;
    Ok(RunBindingHello {
        run_id: utf8(&fields[0])?,
        proxy_origin: utf8(&fields[1])?,
        nonce: utf8(&fields[2])?,
        capability_digest: utf8(&fields[3])?,
    })
}
struct Challenge {
    challenge: Vec<u8>,
    mac: Vec<u8>,
}
fn decode_challenge(frame: &[u8]) -> Result<Challenge, RunBindingError> {
    let fields = decode_fields(frame, HOST_CHALLENGE, &[1, 2])?;
    if fields[0].len() != CHALLENGE_LEN || fields[1].len() != MAC_LEN {
        return Err(RunBindingError::Validation);
    }
    Ok(Challenge {
        challenge: fields[0].clone(),
        mac: fields[1].clone(),
    })
}
struct Response {
    challenge: Vec<u8>,
    capability_digest: String,
    mac: Vec<u8>,
}
fn decode_response(frame: &[u8]) -> Result<Response, RunBindingError> {
    let fields = decode_fields(frame, PROXY_RESPONSE, &[1, 2, 3])?;
    if fields[0].len() != CHALLENGE_LEN || fields[2].len() != MAC_LEN {
        return Err(RunBindingError::Validation);
    }
    Ok(Response {
        challenge: fields[0].clone(),
        capability_digest: utf8(&fields[1])?,
        mac: fields[2].clone(),
    })
}
fn utf8(value: &[u8]) -> Result<String, RunBindingError> {
    String::from_utf8(value.to_vec()).map_err(|_| RunBindingError::Validation)
}
fn validate_hello(hello: &RunBindingHello) -> Result<(), RunBindingError> {
    if !lower_hex_64(&hello.run_id)
        || !lower_hex_64(&hello.nonce)
        || !lower_hex_64(&hello.capability_digest)
        || !valid_origin(&hello.proxy_origin)
    {
        return Err(RunBindingError::Validation);
    }
    Ok(())
}
fn lower_hex_64(value: &str) -> bool {
    value.len() == 64
        && value.bytes().all(|byte| {
            byte.is_ascii_digit() || (byte.is_ascii_lowercase() && byte.is_ascii_hexdigit())
        })
}
fn valid_origin(value: &str) -> bool {
    let Some(port) = value.strip_prefix("http://127.0.0.1:") else {
        return false;
    };
    !port.is_empty()
        && port.bytes().all(|byte| byte.is_ascii_digit())
        && port.parse::<u16>().is_ok_and(|number| number != 0)
}
fn handshake_mac(
    binding_secret: &[u8; 32],
    hello: &RunBindingHello,
    challenge: &[u8],
    role: &[u8],
) -> [u8; 32] {
    hmac_sha256(
        binding_secret,
        &canonical(&[
            b"nomad-run-binding-v1",
            role,
            hello.run_id.as_bytes(),
            hello.proxy_origin.as_bytes(),
            // Public transcript nonce is authenticated but never used as a key.
            hello.nonce.as_bytes(),
            hello.capability_digest.as_bytes(),
            challenge,
        ]),
    )
}
pub(crate) fn canonical(parts: &[&[u8]]) -> Vec<u8> {
    let mut out = Vec::new();
    for part in parts {
        out.extend_from_slice(&(part.len() as u64).to_be_bytes());
        out.extend_from_slice(part);
    }
    out
}
pub(crate) fn hmac_sha256(key: &[u8], message: &[u8]) -> [u8; 32] {
    let mut normalized = [0u8; 64];
    if key.len() > 64 {
        normalized[..32].copy_from_slice(&Sha256::digest(key));
    } else {
        normalized[..key.len()].copy_from_slice(key);
    }
    let mut inner_pad = [0u8; 64];
    let mut outer_pad = [0u8; 64];
    for i in 0..64 {
        inner_pad[i] = normalized[i] ^ 0x36;
        outer_pad[i] = normalized[i] ^ 0x5c;
    }
    let mut digest = Sha256::new();
    digest.update(inner_pad);
    digest.update(message);
    let inner_hash = digest.finalize();
    let mut digest = Sha256::new();
    digest.update(outer_pad);
    digest.update(inner_hash);
    let result = digest.finalize().into();
    normalized.fill(0);
    inner_pad.fill(0);
    outer_pad.fill(0);
    result
}
pub(crate) fn constant_time_eq(left: &[u8], right: &[u8]) -> bool {
    let mut different = left.len() ^ right.len();
    for i in 0..left.len().max(right.len()) {
        different |= usize::from(*left.get(i).unwrap_or(&0) ^ *right.get(i).unwrap_or(&0));
    }
    different == 0
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::{Cursor, Result as IoResult};
    use std::net::Shutdown;
    use std::os::unix::net::UnixStream;
    use std::thread;
    use std::time::{Duration, Instant};
    fn hex(c: char) -> String {
        std::iter::repeat_n(c, 64).collect()
    }
    fn hello() -> RunBindingHello {
        RunBindingHello {
            run_id: hex('a'),
            proxy_origin: "http://127.0.0.1:4444".into(),
            nonce: hex('b'),
            capability_digest: hex('c'),
        }
    }
    struct OneByteIo {
        input: Cursor<Vec<u8>>,
        output: Vec<u8>,
    }
    impl Read for OneByteIo {
        fn read(&mut self, buffer: &mut [u8]) -> IoResult<usize> {
            let length = buffer.len().min(1);
            self.input.read(&mut buffer[..length])
        }
    }
    impl Write for OneByteIo {
        fn write(&mut self, buffer: &[u8]) -> IoResult<usize> {
            if let Some(byte) = buffer.first() {
                self.output.push(*byte);
                Ok(1)
            } else {
                Ok(0)
            }
        }
        fn flush(&mut self) -> IoResult<()> {
            Ok(())
        }
    }
    #[test]
    fn success_over_partial_unix_stream() {
        let (mut host, mut proxy) = UnixStream::pair().unwrap();
        host.set_read_timeout(Some(Duration::from_millis(250)))
            .unwrap();
        host.set_write_timeout(Some(Duration::from_millis(250)))
            .unwrap();
        proxy
            .set_read_timeout(Some(Duration::from_millis(250)))
            .unwrap();
        proxy
            .set_write_timeout(Some(Duration::from_millis(250)))
            .unwrap();
        let expected = hello();
        let secret = [3; 32];
        let worker = thread::spawn(move || proxy_handshake(&mut proxy, expected, secret).unwrap());
        let bound = HostRunBinding::new([7; 32], secret)
            .unwrap()
            .handshake(&mut host)
            .unwrap();
        worker.join().unwrap();
        assert_eq!(bound.run_id, hex('a'));
    }
    #[test]
    fn wrong_out_of_band_secret_fails_with_bounded_liveness() {
        let (mut host_stream, mut proxy_stream) = UnixStream::pair().unwrap();
        for stream in [&host_stream, &proxy_stream] {
            stream
                .set_read_timeout(Some(Duration::from_millis(250)))
                .unwrap();
            stream
                .set_write_timeout(Some(Duration::from_millis(250)))
                .unwrap();
        }
        let worker = thread::spawn(move || {
            let result = proxy_handshake(&mut proxy_stream, hello(), [2; 32]);
            let _ = proxy_stream.shutdown(Shutdown::Both);
            result
        });
        let started = Instant::now();
        let mut host = HostRunBinding::new([1; 32], [3; 32]).unwrap();
        assert!(host.handshake(&mut host_stream).is_err());
        let _ = host_stream.shutdown(Shutdown::Both);
        assert!(started.elapsed() < Duration::from_secs(1));
        assert!(worker.join().unwrap().is_err());
        assert_eq!(host.binding_secret, [0; 32]);
    }
    #[test]
    fn framing_rejects_oversized_and_truncated() {
        let mut oversized = Cursor::new(
            (u32::try_from(MAX_FRAME + 1).unwrap())
                .to_be_bytes()
                .to_vec(),
        );
        assert_eq!(read_frame(&mut oversized), Err(RunBindingError::Frame));
        let mut truncated = Cursor::new(vec![0, 0, 0, 3, 1]);
        assert_eq!(read_frame(&mut truncated), Err(RunBindingError::Io));
    }
    #[test]
    fn framing_handles_partial_reads_and_writes() {
        let mut writer = OneByteIo {
            input: Cursor::new(Vec::new()),
            output: Vec::new(),
        };
        write_frame(&mut writer, b"bounded").unwrap();
        let mut reader = OneByteIo {
            input: Cursor::new(writer.output),
            output: Vec::new(),
        };
        assert_eq!(read_frame(&mut reader).unwrap(), b"bounded");
    }
    #[test]
    fn schema_rejects_unknown_duplicate_and_wrong_version() {
        let mut duplicate = encode_fields(
            HELLO,
            &[(1, b"a"), (1, b"b"), (2, b"c"), (3, b"d"), (4, b"e")],
        )
        .unwrap();
        assert_eq!(decode_hello(&duplicate), Err(RunBindingError::Schema));
        duplicate[1] = 2;
        assert_eq!(decode_hello(&duplicate), Err(RunBindingError::Schema));
        assert_eq!(
            decode_fields(&encode_fields(HELLO, &[(9, b"x")]).unwrap(), HELLO, &[1]),
            Err(RunBindingError::Schema)
        );
    }
    #[test]
    fn facts_reject_invalid_hex_and_origin() {
        let mut value = hello();
        value.run_id = "A".repeat(64);
        assert_eq!(validate_hello(&value), Err(RunBindingError::Validation));
        value = hello();
        value.proxy_origin = "http://127.0.0.1:0".into();
        assert_eq!(validate_hello(&value), Err(RunBindingError::Validation));
        value.proxy_origin = "http://127.0.0.1:22/path".into();
        assert_eq!(validate_hello(&value), Err(RunBindingError::Validation));
    }
    #[test]
    fn bad_mac_wrong_challenge_and_digest_fail_closed() {
        let base = hello();
        let challenge = [9; 32];
        let bad = Response {
            challenge: challenge.to_vec(),
            capability_digest: base.capability_digest.clone(),
            mac: vec![0; 32],
        };
        let secret = [4; 32];
        assert!(!constant_time_eq(
            &bad.mac,
            &handshake_mac(&secret, &base, &challenge, b"proxy")
        ));
        assert_ne!(
            handshake_mac(&secret, &base, &challenge, b"proxy"),
            handshake_mac(&secret, &base, &[8; 32], b"proxy")
        );
        let mut changed = base.clone();
        changed.capability_digest = hex('d');
        assert_ne!(
            handshake_mac(&secret, &base, &challenge, b"proxy"),
            handshake_mac(&secret, &changed, &challenge, b"proxy")
        );
        changed = base.clone();
        changed.nonce = hex('e');
        assert_ne!(
            handshake_mac(&secret, &base, &challenge, b"proxy"),
            handshake_mac(&secret, &changed, &challenge, b"proxy")
        );
    }
    #[test]
    fn replay_and_debug_are_redacted() {
        let mut host = HostRunBinding::new([1; 32], [2; 32]).unwrap();
        let (mut left, _right) = UnixStream::pair().unwrap();
        host.used = true;
        assert_eq!(host.handshake(&mut left), Err(RunBindingError::Replay));
        assert!(!format!("{:?}", hello()).contains(&hex('a')));
        assert!(!format!("{:?}", RunBindingError::Authentication).contains(&hex('b')));
    }
    #[test]
    fn public_nonce_and_captured_frames_cannot_forge_without_binding_secret() {
        let hello = hello();
        let challenge = [7; 32];
        let secret = [8; 32];
        // An observer has all HELLO fields and the Host challenge, but this is
        // not the proxy MAC accepted by a Host holding the separate secret.
        let attacker_guess = hmac_sha256(
            hello.nonce.as_bytes(),
            &canonical(&[
                b"nomad-run-binding-v1",
                b"proxy",
                hello.run_id.as_bytes(),
                hello.proxy_origin.as_bytes(),
                hello.nonce.as_bytes(),
                hello.capability_digest.as_bytes(),
                &challenge,
            ]),
        );
        assert!(!constant_time_eq(
            &attacker_guess,
            &handshake_mac(&secret, &hello, &challenge, b"proxy")
        ));
        assert_ne!(
            handshake_mac(&[9; 32], &hello, &challenge, b"proxy"),
            handshake_mac(&secret, &hello, &challenge, b"proxy")
        );
    }
    #[test]
    fn captured_response_cannot_be_replayed_after_public_nonce_substitution() {
        let original = hello();
        let mut substituted = original.clone();
        substituted.nonce = hex('f');
        let secret = [6; 32];
        let challenge = [7; 32];
        let captured_proxy_mac = handshake_mac(&secret, &original, &challenge, b"proxy");
        assert!(!constant_time_eq(
            &captured_proxy_mac,
            &handshake_mac(&secret, &substituted, &challenge, b"proxy")
        ));
    }
    #[test]
    fn secret_never_occurs_in_hello_or_challenge_frames_and_is_zeroized() {
        let secret = [0x5a; 32];
        let hello = hello();
        let hello_frame = encode_fields(
            HELLO,
            &[
                (1, hello.run_id.as_bytes()),
                (2, hello.proxy_origin.as_bytes()),
                (3, hello.nonce.as_bytes()),
                (4, hello.capability_digest.as_bytes()),
            ],
        )
        .unwrap();
        let challenge_frame = encode_fields(
            HOST_CHALLENGE,
            &[
                (1, &[7; 32]),
                (2, &handshake_mac(&secret, &hello, &[7; 32], b"host")),
            ],
        )
        .unwrap();
        assert!(!hello_frame
            .windows(secret.len())
            .any(|window| window == secret));
        assert!(!challenge_frame
            .windows(secret.len())
            .any(|window| window == secret));
        let mut host = HostRunBinding::new([7; 32], secret).unwrap();
        let mut truncated = Cursor::new(vec![0, 0, 0, 1]);
        let _ = host.handshake(&mut truncated);
        assert_eq!(host.binding_secret, [0; 32]);
    }
}
